spring:
  application:
    name: jpa-transactions

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jpa-transactions.db
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    kr.co.pincoin: DEBUG
    org.hibernate.SQL: DEBUG
